export const MARKET_ABI = [
  // Price update events
  {
    type: 'event',
    name: 'PriceUpdated',
    inputs: [
      { name: 'newPrice', type: 'uint256', indexed: false },
      { name: 'oracleTimestamp', type: 'uint256', indexed: false },
      { name: 'navAfter', type: 'uint256', indexed: false },
      { name: 'navStAfter', type: 'uint256', indexed: false },
      { name: 'navJtAfter', type: 'uint256', indexed: false },
      { name: 'jtStRatioAfter', type: 'uint256', indexed: false },
      { name: 'halted', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DepositYT',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'asSenior', type: 'bool', indexed: true },
      { name: 'assets', type: 'uint256', indexed: false },
      { name: 'shares', type: 'uint256', indexed: false },
      { name: 'depositValue', type: 'uint256', indexed: false },
      { name: 'navAfter', type: 'uint256', indexed: false },
      { name: 'navStAfter', type: 'uint256', indexed: false },
      { name: 'navJtAfter', type: 'uint256', indexed: false },
      { name: 'jtStRatioAfter', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'WithdrawYT',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'fromSenior', type: 'bool', indexed: true },
      { name: 'byShares', type: 'bool', indexed: false },
      { name: 'sharesIn', type: 'uint256', indexed: false },
      { name: 'assetsOut', type: 'uint256', indexed: false },
      { name: 'withdrawValue', type: 'uint256', indexed: false },
      { name: 'navAfter', type: 'uint256', indexed: false },
      { name: 'navStAfter', type: 'uint256', indexed: false },
      { name: 'navJtAfter', type: 'uint256', indexed: false },
      { name: 'jtStRatioAfter', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DepositRequested',
    inputs: [
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'user', type: 'address', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'asSenior', type: 'bool', indexed: false },
      { name: 'tokenIn', type: 'address', indexed: false },
      { name: 'amountIn', type: 'uint256', indexed: false },
      { name: 'minYtOut', type: 'uint256', indexed: false },
      { name: 'referrerId', type: 'bytes32', indexed: false },
      { name: 'extraData', type: 'bytes', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DepositBasePulled',
    inputs: [
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'to', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'DepositSettled',
    inputs: [
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'asSenior', type: 'bool', indexed: false },
      { name: 'ytIn', type: 'uint256', indexed: false },
      { name: 'sharesMinted', type: 'uint256', indexed: false },
      { name: 'depositValue', type: 'uint256', indexed: false },
      { name: 'navAfter', type: 'uint256', indexed: false },
      { name: 'navStAfter', type: 'uint256', indexed: false },
      { name: 'navJtAfter', type: 'uint256', indexed: false },
      { name: 'jtStRatioAfter', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DepositRejected',
    inputs: [
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'reasonCode', type: 'uint32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DepositRefunded',
    inputs: [
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'tokenIn', type: 'address', indexed: false },
      { name: 'amountIn', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MarketHaltedEvent',
    inputs: [
      { name: 'oracleTimestamp', type: 'uint256', indexed: false },
      { name: 'lastPrice', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CarryFeeAccrued',
    inputs: [
      { name: 'feeYt', type: 'uint256', indexed: false },
      { name: 'feeBase', type: 'uint256', indexed: false },
      { name: 'updateCase', type: 'uint8', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CarryFeeCollected',
    inputs: [
      { name: 'to', type: 'address', indexed: true },
      { name: 'feeYt', type: 'uint256', indexed: false },
    ],
  },
] as const;
